### ISSUE TITLE
Fail to install if languages folder is empty

### ISSUE THREAD

**Issue by runthis** [wp-cli/language-command#123]
## Bug Report

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [x] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

If the current languages folder is empty, running `wp language core install <lang>` will result in a warning followed by a failed install.

**Describe how other contributors can replicate this bug**

If assuming this is not related to our non-standard WordPress setup, replication steps are:

- Delete all files in the languages folder
- Attempt to install a language using wp-cli

**Describe what you would expect as the correct outcome**

If the issue is difficult to resolve, a potentially better error message would be convenient in this use-case. Tracking down the issue didn't take -too long- but on a hunch I created an empty file in the languages folder after ruling out other issues (which resolved the issue). I then deleted all files in the languages folder and was able to consistently replicate the failed install.

**Let us know what environment you are running this on**

Docker, bedrock, php 8.2, wordpress 6.2

```
$ docker-compose exec -u www-data -w /var/www/html wordpress wp language core install da_DK
Using cached file '/home/www-data/.wp-cli/cache/translation/core-default-6.2.2-da_DK-1689336729.zip'...
Unpacking the update...
Installing the latest version...
Removing the old version of the translation...
Warning: The destination directory already exists and could not be removed.
Translation update failed.
Warning: Could not install language 'da_DK'.
Language 'da_DK' not installed.
Error: No languages installed (1 failed).
```

**Provide a possible solution**

I could not find directly where this happens to offer a better solution, my apologies.

**Comment by swissspidy** [comment]
This sounds like a file permission issue specific to your setup. I am unable to reproduce this and the following Behat test passes:

```gherkin
  Scenario: Install language with an empty languages directory
    Given a WP install
    And an empty cache
    And an empty wp-content/languages directory

    When I run `wp language core install da_DK`
    Then the wp-content/languages/admin-da_DK.po file should exist
    And the wp-content/languages/da_DK.po file should exist
    And STDOUT should contain:
      """
      Success: Installed 1 of 1 languages.
      """
    And STDERR should be empty
```

Some background:

If the languages directory is empty, `\WP_Upgrader::install_package()` in WordPress calls `move_dir()` to move the downloaded translations to the desired location. The error happens in `move_dir()` because it can't delete the target directory.

If the directory is not empty, WP uses a different function `copy_dir()` to copy the files around. That's why you see different behavior in that scenario.

**Comment by runthis** [comment]
Fair enough. I have a pretty non-standard installation going. If it works for you I think this issue can be closed. For anyone in the future who sees something similar, The work-around I chose when running an initial setup script is to touch a new file in the folder and delete it after all the languages needed are installed.

**Comment by XVII** [comment]
Thanks from the future. The error is kinda vague and didn't clearly state a permission problem!

**Comment by XVII** [comment]
Just some further context for my version of this issue if it helps someone -- it was actually due to the permissions on the parent folder. The language updater in core tries to do some delete/recreate doesn't quite handle it gracefully enough (even if empty) causing the failure.

> "But my permissions look right? On parent folders too..." - me

Yeh, this had me confused. I realised that it was because I had mounted `/wp-content/languages` as a volume. That dir can't be removed/re-created within the container because it's "in use".

The workaround I use was to define `WP_LANG_DIR` as a subdirectory of `/wp-content/languages` instead which let me mount it.

```
define( 'WP_LANG_DIR', __DIR__ . '/wp-content/languages/files' );
````

towards the end of the editable section in `wp-config.php` helped push the files into a subdirectory. The updates commands now work and I can still mount it which saves the container re-downloading every language every time.
