### ISSUE TITLE
Clarify docs arugment

### ISSUE THREAD

**Issue by timotheemoulin** [wp-cli/language-command#90]
Can we update the example in the doc and add one with the full locale? I think that could help.

e.g.

```
wp language core install fr_FR
```

or at least write something in the *options* section under the `<language>` chapter.

**Comment by danielbachhuber** [comment]
@timotheemoulin I'm not sure I understand your suggestion... want to submit a pull request with your suggested change?

**Comment by ernilambar** [comment]
@danielbachhuber 

Let me jot down my understanding here.

https://developer.wordpress.org/cli/commands/language/core/install/ - `wp language core install <language>... [--activate]`

`<language>` - `Language code to install.`

We have mentioned language code. But in our WordPress context, Language Code is different than WordPress Locale Code.

For Nepali language, language code is `ne` but WP locale code is `ne_NP`.
But some languages have same language code and locale code like `ja`, `ar`, etc.

In our docs, it is not particularly clear that we should use `ne_NP` instead of `ne`. In the example also, we have used Japanese which coincidently happens to have same language code and locale code.
So I believe OP is asking to clarify this confusion in the docs and examples.

**Comment by danielbachhuber** [comment]
@ernilambar Thanks for clarifying — that makes sense!

**Comment by UmeshSingla** [comment]
Working on it.

**Comment by swissspidy** [comment]
Fixed by #153
